apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualmachines.chanwit.github.com
spec:
  group: chanwit.github.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: virtualmachines
    singular: virtualmachine
    kind: VirtualMachine
    shortNames:
      - vm
      - vms
  additionalPrinterColumns:
    - name: Kernel
      type: string
      description: Kernel image name
      JSONPath: .spec.kernel
    - name: Image
      type: string
      description: RootFS image name
      JSONPath: .spec.image
    - name: Cpus
      type: integer
      description: CPU
      JSONPath: .spec.cpus
    - name: Memory
      type: string
      description: Memory
      JSONPath: .spec.memory
    - name: Size
      type: string
      description: Disk's size
      JSONPath: .spec.diskSize
    - name: State
      type: string
      priority: 0
      JSONPath: .status.state
      description: VM state
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          properties:
            kernel:
              type: string
            image:
              type: string
            cpus:
              type: integer
            memory:
              type: string
            diskSize:
              type: string
