apiVersion: v1
kind: Pod
metadata:
  name: my-vm
spec:
  containers:
  - name: rootfs
    imagePullPolicy: Always
    image: weaveworks/ignite-ubuntu
    resources:
      requests:
        memory: 512M
        cpu: 1
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/role: agent
    beta.kubernetes.io/os: linux
    type: virtual-kubelet
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
